services:
  payment:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_NAME=cashapp
      - PG_USER=user
      - PG_PASS=password
      - PG_SSLMODE=disable
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_URL=
      - DATABASE_URL=
      - PORT=9001
      - ENV=dev
      - RUN_SEEDS=true
    ports:
      - "9001:9001"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${PG_NAME:-cashapp}
      - POSTGRES_USER=${PG_USER:-user}
      - POSTGRES_PASSWORD=${PG_PASS:-password}
      - PGPORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
