services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5455:5455"
    environment:
      - PORT=5455
      - FILE=http://fileserver:9000/
      - PAYMENT=http://payment:9001/
      - MANAGEMENT=http://management:9002/
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5455/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana

networks:
  monitoring: