services:
  rms-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    command: /code/scripts/run.sh
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_NAME=
      - DATABASE_PORT=
      - REDIS_DB=
      - REDIS_PASSWORD=
      - REDIS_HOST=
      - REDIS_PORT=
      - REDIS_URL=
      - SECRET_KEY=
      - ALGORITHM=
      - ACCESS_TOKEN_EXPIRE_MINUTES=

  postgres:
    image: "blackprince/rms-geodb-base:0.1.4"
    ports:
      - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

  redis:
    image: "redis/redis-stack"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  pgdata:
  redis-data:

